User notifications fixes
open-company/open-company-digest pull request #9
Opened 2018-11-02 13:32 UTC by bago2k4

Main PR: https://github.com/open-company/open-company-web/pull/728

2018-11-02 13:37 UTC, bago2k4 commented
![](https://github.trello.services/images/mini-trello-icon.png) [In-app digest medium](https://trello.com/c/ItvVtQQS/1665-in-app-digest-medium)

2018-11-05 18:56 UTC, thepug requested changes

2018-11-05 18:56 UTC, thepug commented on src/oc/digest/resources/user.clj
> +  ([user :guard #(and (= (keyword (:digest-medium %)) :email) = (keyword (:status %)) :active)] true) ; active email user
@bago2k4 does this syntax work? you have a bare `=` after that first and condition

2018-11-05 19:06 UTC, bago2k4 commented
@thepug fixed the issue, maybe to make sure check with a dry run that digest are not sent to not verified email users (that error was probably failing on the status check)

2018-11-05 19:07 UTC, thepug approved these changes

2018-11-05 19:13 UTC, merged